Asp_presentacion/Pages/Ventanas/Auditorias.cshtml.cs
using Lib_entidades;
using Lib_presentaciones.Interfaces;
using Lib_utilidades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Asp_presentacion.Pages.Ventanas
{
    public class AuditoriasModel : PageModel
    {
        private IAuditoriasPresentacion? iPresentacion = null;

        public AuditoriasModel(IAuditoriasPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Auditorias();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Auditorias? Actual { get; set; }
        [BindProperty] public Auditorias? Filtro { get; set; }
        [BindProperty] public List<Auditorias>? Lista { get; set; }
        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                Filtro!.Usuario = Filtro!.Usuario ?? "";
                Filtro!.Fecha = DateTime.Now;

                Accion = Enumerables.Ventanas.Listas;
                var task = this.iPresentacion!.Buscar(Filtro!, "Usuario");
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Auditorias()
                {
                    Fecha = DateTime.Now,
                };
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Task<Auditorias>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!);
                else
                    task = this.iPresentacion!.Modificar(Actual!);
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

Asp_presentacion/Pages/Ventanas/Bodega.cshtml.cs
using Lib_entidades;
using Lib_presentaciones.Interfaces;
using Lib_utilidades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Asp_presentacion.Pages.Ventanas
{
    public class BodegaModel : PageModel
    {
        private IBodegaPresentacion? iPresentacion = null;

        public BodegaModel(IBodegaPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Bodega();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Bodega? Actual { get; set; }
        [BindProperty] public Bodega? Filtro { get; set; }
        [BindProperty] public List<Bodega>? Lista { get; set; }
        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                Filtro!.Nombre = Filtro!.Nombre ?? "";

                Accion = Enumerables.Ventanas.Listas;
                var task = this.iPresentacion!.Buscar(Filtro!, "NOMBRE");
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Bodega()
                {
                };
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Task<Bodega>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!);
                else
                    task = this.iPresentacion!.Modificar(Actual!);
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

Asp_presentacion/Pages/Ventanas/Estante.cshtml.cs
using Lib_entidades;
using Lib_presentaciones.Interfaces;
using Lib_utilidades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Asp_presentacion.Pages.Ventanas
{
    public class EstanteModel : PageModel
    {
        private IEstantePresentacion? iPresentacion = null;

        public EstanteModel(IEstantePresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Estante();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Estante? Actual { get; set; }
        [BindProperty] public Estante? Filtro { get; set; }
        [BindProperty] public List<Estante>? Lista { get; set; }
        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                Filtro!.Nombre = Filtro!.Nombre ?? "";

                Accion = Enumerables.Ventanas.Listas;
                var task = this.iPresentacion!.Buscar(Filtro!, "NOMBRE");
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Estante()
                {
                };
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Task<Estante>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!);
                else
                    task = this.iPresentacion!.Modificar(Actual!);
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

Asp_presentacion/Pages/Ventanas/Proveedor.cshtml.cs
using Lib_entidades;
using Lib_presentaciones.Interfaces;
using Lib_utilidades;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Asp_presentacion.Pages.Ventanas
{
    public class ProveedorModel : PageModel
    {
        private IProveedorPresentacion? iPresentacion = null;

        public ProveedorModel(IProveedorPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Proveedor();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Proveedor? Actual { get; set; }
        [BindProperty] public Proveedor? Filtro { get; set; }
        [BindProperty] public List<Proveedor>? Lista { get; set; }
        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                Filtro!.Nombre = Filtro!.Nombre ?? "";

                Accion = Enumerables.Ventanas.Listas;
                var task = this.iPresentacion!.Buscar(Filtro!, "NOMBRE");
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Proveedor()
                {
                };
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Task<Proveedor>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!);
                else
                    task = this.iPresentacion!.Modificar(Actual!);
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

Asp_presentacion/Pages/Ventanas/Bodega.cshtml
@page
@model Asp_presentacion.Pages.Ventanas.BodegaModel
@{
    ViewData["Titulo"] = Lib_lenguajes.RsMenu.lbBodega;
}
<center>
    <div>
        <form method="POST"
              enctype="multipart/form-data">
            @Html.AntiForgeryToken()

            <div align="left">
                <h3>@Lib_lenguajes.RsMenu.lbBodega</h3>
            </div>
            <div align="left"
                 class="bt_panel_buttons">
                <input type="submit"
                       value="@Lib_lenguajes.RsMenu.lbRefrescar"
                       asp-page-handler="BtRefrescar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion != Lib_utilidades.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="@Lib_lenguajes.RsMenu.lbNuevo"
                       asp-page-handler="BtNuevo"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion != Lib_utilidades.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="@Lib_lenguajes.RsMenu.lbGuardar"
                       asp-page-handler="BtGuardar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion == Lib_utilidades.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="@Lib_lenguajes.RsMenu.lbCancelar"
                       asp-page-handler="BtCancelar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion == Lib_utilidades.Enumerables.Ventanas.Listas)" />
            </div>

            @if (Model.Accion != Lib_utilidades.Enumerables.Ventanas.Listas ||
            Model.Accion == Lib_utilidades.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Id" />
            }
            @if (Model.Accion == Lib_utilidades.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Nombre" />
            }

            @if (Model.Accion == Lib_utilidades.Enumerables.Ventanas.Editar)
            {
                <div class="containers_vn panel panel-default">
                    <h3>@Lib_lenguajes.RsBodega.lbSingular</h3>

                    <div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                @Lib_lenguajes.RsBodega.lbNombre
                            </label>
                            <div class="col-lg-6">
                                <input id="nmNombre"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Nombre" />
                            </div>
                            <label class="col-lg-4 control-label">
                                @Lib_lenguajes.RsBodega.lbCodigoBodega
                            </label>
                            <div class="col-lg-6">
                                <input id="nmCodigoBodega"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.CodigoBodega" />
                            </div>
                            <label class="col-lg-4 control-label">
                                @Lib_lenguajes.RsBodega.lbCodigoSucursal
                            </label>
                            <div class="col-lg-6">
                                <input id="nmCodigoSucursal"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.CodigoSucursal" />
                            </div>
                        </div>
                    </div>
                </div>
            }

            @if (ViewData.ContainsKey("Mensaje"))
            {
                <input type="hidden"
                       asp-for="@Model.Accion" />
                @await Html.PartialAsync(
                         "../Emergentes/Mensajes.cshtml")
            }

            @if (Model.Accion == Lib_utilidades.Enumerables.Ventanas.Borrar)
            {
                <div class='popup'>
                    <div class='pp_del_inner'>
                        <div style='width:95%'>
                            <h2 align="left">
                                @Lib_lenguajes.RsMenu.lbMensaje
                            </h2>

                            <h4 align="left">
                                @Lib_lenguajes.RsMenu.lbBorrarEntidad
                            </h4>
                            <h6 align="left">
                                @Model.Actual!.Nombre
                            </h6>
                            <br />
                            <br />
                            <input type="submit"
                                   value="@Lib_lenguajes.RsMenu.lbBorrar"
                                   asp-page-handler="BtBorrar"
                                   class="btn btn-secondary" />
                            <input type="submit"
                                   value="@Lib_lenguajes.RsMenu.lbCerrar"
                                   asp-page-handler="BtCancelar"
                                   class="btn btn-secondary" />
                        </div>
                    </div>
                </div>
            }

            @if (Model.Accion == Lib_utilidades.Enumerables.Ventanas.Listas ||
            Model.Accion == Lib_utilidades.Enumerables.Ventanas.Borrar)
            {
                <input id="flNombre"
                       class="cts_forms form-control"
                       asp-for="@Model.Filtro!.Nombre"
                       placeholder="@Lib_lenguajes.RsBodega.lbNombre" />
                <br />

                <div class="containers_vn panel panel-default">
                    <table class="tb_data table table-striped table-bordered table-hover">
                        <tr>
                            <th>
                                @Lib_lenguajes.RsBodega.clNombre
                            </th>
                            <th>
                                @Lib_lenguajes.RsBodega.clCodigoBodega
                            </th>
                            <th>
                                @Lib_lenguajes.RsBodega.clCodigoSucursal
                            </th>
                            <th class="cl_actions">
                                @Lib_lenguajes.RsMenu.lbAccion
                            </th>
                        </tr>
                        @if (Model != null && Model.Lista != null)
                        {
                            @foreach (var elemento in Model.Lista)
                            {
                                <tr>
                                    <td>
                                        @elemento.Nombre
                                    </td>
                                    <td>
                                        @elemento.CodigoBodega
                                    </td>
                                    <td>
                                        @elemento.CodigoSucursal
                                    </td>
                                    <td>
                                        <input type="submit"
                                               value="@Lib_lenguajes.RsMenu.lbModicar"
                                               asp-page-handler="BtModificar"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                        <input type="submit"
                                               value="@Lib_lenguajes.RsMenu.lbBorrar"
                                               asp-page-handler="BtBorrarVal"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            }
        </form>
    </div>
</center>